//Export cooking recipes to be used in script

//Array of objects containing the recipes in DDV
let cookingRecipes = [
    {
        "Recipe": "Apple Cider Glazed Salmon",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Salmon",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1572",
        "sellPrice": "271",
    },
    {
        "Recipe": "Apple Pie",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1137",
        "sellPrice": "303",
    },
    {
        "Recipe": "Apple Sorbet",
        "Stars": "3",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Apple",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1077",
        "sellPrice": "271",
    },
    {
        "Recipe": "Arendellian Pickled Herring",
        "Stars": "5",
        "Ingredient1": "Herring",
        "Ingredient2": "Lemon",
        "Ingredient3": "Onion",
        "Ingredient4": "Garlic",
        "Ingredient5": "Any spice",
        "Energy": "2102",
        "sellPrice": "556",
    },
    {
        "Recipe": "Aurora's Cake",
        "Stars": "5",
        "Ingredient1": "Raspberry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Milk",
        "Energy": "2030",
        "sellPrice": "786",
    },
    {
        "Recipe": "Baked Carp",
        "Stars": "2",
        "Ingredient1": "Carp",
        "Ingredient2": "Butter",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1894",
        "sellPrice": "767",
    },
    {
        "Recipe": "Banana Ice Cream",
        "Stars": "4",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1884",
        "sellPrice": "641",
    },
    {
        "Recipe": "Banana Pie",
        "Stars": "3",
        "Ingredient1": "Banana",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1227",
        "sellPrice": "308",
    },
    {
        "Recipe": "Banana Split",
        "Stars": "5",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "Any sweets",
        "Energy": "2252",
        "sellPrice": "780",
    },
    {
        "Recipe": "Basil Omelet",
        "Stars": "4",
        "Ingredient1": "Basil",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "2033",
        "sellPrice": "982",
    },
]


/*{
        "Recipe": "",
        "Stars": "",
        "Ingredient1": "",
        "Ingredient2": "",
        "Ingredient3": "",
        "Ingredient4": "",
        "Ingredient5": "",
        "Energy": "",
        "sellPrice": "",
    },
*/