//Export cooking recipes to be used in script

//Array of objects containing the recipes in DDV
let cookingRecipes = [
    {
        "Recipe": "Apple Cider Glazed Salmon",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Salmon",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1572",
        "sellPrice": "271",
    },
    {
        "Recipe": "Apple Pie",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1137",
        "sellPrice": "303",
    },
    {
        "Recipe": "Apple Sorbet",
        "Stars": "3",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Apple",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1077",
        "sellPrice": "271",
    },
    {
        "Recipe": "Arendellian Pickled Herring",
        "Stars": "5",
        "Ingredient1": "Herring",
        "Ingredient2": "Lemon",
        "Ingredient3": "Onion",
        "Ingredient4": "Garlic",
        "Ingredient5": "Spice",
        "Energy": "2102",
        "sellPrice": "556",
    },
    {
        "Recipe": "Aurora's Cake",
        "Stars": "5",
        "Ingredient1": "Raspberry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Milk",
        "Energy": "2030",
        "sellPrice": "786",
    },
    {
        "Recipe": "Baked Carp",
        "Stars": "2",
        "Ingredient1": "Carp",
        "Ingredient2": "Butter",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1894",
        "sellPrice": "767",
    },
    {
        "Recipe": "Banana Ice Cream",
        "Stars": "4",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1884",
        "sellPrice": "641",
    },
    {
        "Recipe": "Banana Pie",
        "Stars": "3",
        "Ingredient1": "Banana",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1227",
        "sellPrice": "308",
    },
    {
        "Recipe": "Banana Split",
        "Stars": "5",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "Sweets",
        "Energy": "2252",
        "sellPrice": "780",
    },
    {
        "Recipe": "Basil Omelet",
        "Stars": "4",
        "Ingredient1": "Basil",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "2033",
        "sellPrice": "982",
    },
    {
        "Recipe": "Beignets",
        "Stars": "4",
        "Ingredient1": "Canola",
        "Ingredient2": "Wheat",
        "Ingredient3": "Egg",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "912",
        "sellPrice": "524",
    },
    {
        "Recipe": "Bell Pepper Puffs",
        "Stars": "3",
        "Ingredient1": "Bell Pepper",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1272",
        "sellPrice": "606",
    },
    {
        "Recipe": "Berry Salad",
        "Stars": "3",
        "Ingredient1": "Blueberry",
        "Ingredient2": "Gooseberry",
        "Ingredient3": "Raspberry",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2210",
        "sellPrice": "139",
    },
    {
        "Recipe": "Birthday Cake",
        "Stars": "5",
        "Ingredient1": "Cocoa Bean",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Butter",
        "Energy": "2310",
        "sellPrice": "749",
    },
    {
        "Recipe": "Biscuits",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "679",
        "sellPrice": "294",
    },
    {
        "Recipe": "Blueberry Pie",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Butter",
        "Ingredient3": "Blueberry",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1227",
        "sellPrice": "308",
    },
    {
        "Recipe": "Bouillabaisse",
        "Stars": "5",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Shellfish",
        "Ingredient3": "Shrimp",
        "Ingredient4": "Tomato",
        "Ingredient5": "Vegetable",
        "Energy": "2132",
        "sellPrice": "684",
    },
    {
        "Recipe": "",
        "Stars": "",
        "Ingredient1": "",
        "Ingredient2": "",
        "Ingredient3": "",
        "Ingredient4": "",
        "Ingredient5": "",
        "Energy": "",
        "sellPrice": "",
    },
]


/*{
        "Recipe": "",
        "Stars": "",
        "Ingredient1": "",
        "Ingredient2": "",
        "Ingredient3": "",
        "Ingredient4": "",
        "Ingredient5": "",
        "Energy": "",
        "sellPrice": "",
    },
*/