//Export cooking recipes to be used in script

//Array of objects containing the recipes in DDV
let cookingRecipes = [
    {
        "Recipe": "Apple Cider Glazed Salmon",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Salmon",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1572",
        "sellPrice": "271",
    },
    {
        "Recipe": "Apple Pie",
        "Stars": "3",
        "Ingredient1": "Apple",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1137",
        "sellPrice": "303",
    },
    {
        "Recipe": "Apple Sorbet",
        "Stars": "3",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Apple",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1077",
        "sellPrice": "271",
    },
    {
        "Recipe": "Arendellian Pickled Herring",
        "Stars": "5",
        "Ingredient1": "Herring",
        "Ingredient2": "Lemon",
        "Ingredient3": "Onion",
        "Ingredient4": "Garlic",
        "Ingredient5": "Spice",
        "Energy": "2102",
        "sellPrice": "556",
    },
    {
        "Recipe": "Aurora's Cake",
        "Stars": "5",
        "Ingredient1": "Raspberry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Milk",
        "Energy": "2030",
        "sellPrice": "786",
    },
    {
        "Recipe": "Baked Carp",
        "Stars": "2",
        "Ingredient1": "Carp",
        "Ingredient2": "Butter",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1894",
        "sellPrice": "767",
    },
    {
        "Recipe": "Banana Ice Cream",
        "Stars": "4",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1884",
        "sellPrice": "641",
    },
    {
        "Recipe": "Banana Pie",
        "Stars": "3",
        "Ingredient1": "Banana",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1227",
        "sellPrice": "308",
    },
    {
        "Recipe": "Banana Split",
        "Stars": "5",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "Banana",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "Sweets",
        "Energy": "2252",
        "sellPrice": "780",
    },
    {
        "Recipe": "Basil Omelet",
        "Stars": "4",
        "Ingredient1": "Basil",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "2033",
        "sellPrice": "982",
    },
    {
        "Recipe": "Beignets",
        "Stars": "4",
        "Ingredient1": "Canola",
        "Ingredient2": "Wheat",
        "Ingredient3": "Egg",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "912",
        "sellPrice": "524",
    },
    {
        "Recipe": "Bell Pepper Puffs",
        "Stars": "3",
        "Ingredient1": "Bell Pepper",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1272",
        "sellPrice": "606",
    },
    {
        "Recipe": "Berry Salad",
        "Stars": "3",
        "Ingredient1": "Blueberry",
        "Ingredient2": "Gooseberry",
        "Ingredient3": "Raspberry",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2210",
        "sellPrice": "139",
    },
    {
        "Recipe": "Birthday Cake",
        "Stars": "5",
        "Ingredient1": "Cocoa Bean",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Butter",
        "Energy": "2310",
        "sellPrice": "749",
    },
    {
        "Recipe": "Biscuits",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "679",
        "sellPrice": "294",
    },
    {
        "Recipe": "Blueberry Pie",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Butter",
        "Ingredient3": "Blueberry",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1227",
        "sellPrice": "308",
    },
    {
        "Recipe": "Bouillabaisse",
        "Stars": "5",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Shellfish",
        "Ingredient3": "Shrimp",
        "Ingredient4": "Tomato",
        "Ingredient5": "Vegetable",
        "Energy": "2132",
        "sellPrice": "684",
    },
    {
        "Recipe": "Candy",
        "Stars": "1",
        "Ingredient1": "Sweets",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "266",
        "sellPrice": "72",
    },
    {
        "Recipe": "Caramel Apples",
        "Stars": "2",
        "Ingredient1": "Apple",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "638",
        "sellPrice": "56",
    },
    {
        "Recipe": "Carp Salad",
        "Stars": "3",
        "Ingredient1": "Carp",
        "Ingredient2": "Lemon",
        "Ingredient3": "Lettuce",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2310",
        "sellPrice": "617",
    },
    {
        "Recipe": "Carrot Cake",
        "Stars": "Carrot",
        "Ingredient1": "Wheat",
        "Ingredient2": "Egg",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "908",
        "sellPrice": "427",
    },
    {
        "Recipe": "Cheese Platter",
        "Stars": "1",
        "Ingredient1": "Cheese",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "482",
        "sellPrice": "216",
    },
    {
        "Recipe": "Cheesecake",
        "Stars": "4",
        "Ingredient1": "Cheese",
        "Ingredient2": "Wheat",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Fruit",
        "Ingredient5": "-",
        "Energy": "1161",
        "sellPrice": "332",
    },
    {
        "Recipe": "Cheesy Crispy Baked Cod",
        "Stars": "3",
        "Ingredient1": "Cod",
        "Ingredient2": "Wheat",
        "Ingredient3": "Cheese",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "840",
        "sellPrice": "303",
    },
    {
        "Recipe": "Cherry Pie",
        "Stars": "3",
        "Ingredient1": "Cherry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1497",
        "sellPrice": "326",
    },
    {
        "Recipe": "Chili Pepper Puffs",
        "Stars": "3",
        "Ingredient1": "Chili Pepper",
        "Ingredient2": "Egg",
        "Ingredient3": "Cheese",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1382",
        "sellPrice": "669",
    },
    {
        "Recipe": "Chocolate Chip Cookies",
        "Stars": "4",
        "Ingredient1": "Cocoa Bean",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1569",
        "sellPrice": "373",
    },
    {
        "Recipe": "Chocolate Ice Cream",
        "Stars": "4",
        "Ingredient1": "Cocoa Bean",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Milk",
        "Ingredient4": "Slush Ice",
        "Ingredient5": "-",
        "Energy": "2074",
        "sellPrice": "665",
    },
    {
        "Recipe": "Chocolate Waffles",
        "Stars": "4",
        "Ingredient1": "Cocoa Bean",
        "Ingredient2": "Wheat",
        "Ingredient3": "Egg",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "2223",
        "sellPrice": "735",
    },
    {
        "Recipe": "Chowder",
        "Stars": "4",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Milk",
        "Ingredient4": "Potato",
        "Ingredient5": "-",
        "Energy": "1204",
        "sellPrice": "625",
    },
    {
        "Recipe": "Coconut Cake",
        "Stars": "4",
        "Ingredient1": "Coconut",
        "Ingredient2": "Wheat",
        "Ingredient3": "Egg",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1750",
        "sellPrice": "424",
    },
    {
        "Recipe": "Crackers",
        "Stars": "1",
        "Ingredient1": "Grain",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "80",
        "sellPrice": "2",
    },
    {
        "Recipe": "Creamy Garlic Scallops",
        "Stars": "4",
        "Ingredient1": "Scallops",
        "Ingredient2": "Lemon",
        "Ingredient3": "Garlic",
        "Ingredient4": "Butter",
        "Ingredient5": "-",
        "Energy": "1844",
        "sellPrice": "499",
    },
    {
        "Recipe": "Creamy Soup",
        "Stars": "4",
        "Ingredient1": "Spice",
        "Ingredient2": "Milk",
        "Ingredient3": "Potato",
        "Ingredient4": "Vegetable",
        "Ingredient5": "-",
        "Energy": "1166",
        "sellPrice": "595",
    },
    {
        "Recipe": "Crepe",
        "Stars": "4",
        "Ingredient1": "Wheat",
        "Ingredient2": "Egg",
        "Ingredient3": "Milk",
        "Ingredient4": "Vanilla",
        "Ingredient5": "-",
        "Energy": "1624",
        "sellPrice": "768",
    },
    {
        "Recipe": "Crispy Baked Cod",
        "Stars": "2",
        "Ingredient1": "Cod",
        "Ingredient2": "Wheat",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "337",
        "sellPrice": "47",
    },
    {
        "Recipe": "Crudites",
        "Stars": "1",
        "Ingredient1": "Carrot",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "141",
        "sellPrice": "52",
    },
    {
        "Recipe": "Eggplant Puffs",
        "Stars": "3",
        "Ingredient1": "Eggplant",
        "Ingredient2": "Cheese",
        "Ingredient3": "Egg",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1941",
        "sellPrice": "991",
    },
    {
        "Recipe": "Fish 'n' Chips",
        "Stars": "4",
        "Ingredient1": "Fish",
        "Ingredient2": "Wheat",
        "Ingredient3": "Potato",
        "Ingredient4": "Canola",
        "Ingredient5": "-",
        "Energy": "697",
        "sellPrice": "392",
    },
    {
        "Recipe": "Fish Creole",
        "Stars": "5",
        "Ingredient1": "Fish",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Rice",
        "Ingredient4": "Tomato",
        "Ingredient5": "Garlic",
        "Energy": "840",
        "sellPrice": "293",
    },
    {
        "Recipe": "Fish Pasta",
        "Stars": "4",
        "Ingredient1": "Fish",
        "Ingredient2": "Wheat",
        "Ingredient3": "Garlic",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "1282",
        "sellPrice": "475",
    },
    {
        "Recipe": "Fish Pie",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "867",
        "sellPrice": "303",
    },
    {
        "Recipe": "Fish Risotto",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Rice",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "939",
        "sellPrice": "386",
    },
    {
        "Recipe": "Fish Salad",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Lettuce",
        "Ingredient3": "Lemon",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1140",
        "sellPrice": "92",
    },
    {
        "Recipe": "Fish Sandwiches",
        "Stars": "2",
        "Ingredient1": "Fish",
        "Ingredient2": "Wheat",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "337",
        "sellPrice": "34",
    },
    {
        "Recipe": "Fish Soup",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Milk",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "995",
        "sellPrice": "379",
    },
    {
        "Recipe": "Fish Steak",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Tomato",
        "Ingredient3": "Basil",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "537",
        "sellPrice": "100",
    },
    {
        "Recipe": "Fish Tacos",
        "Stars": "4",
        "Ingredient1": "Fish",
        "Ingredient2": "Corn",
        "Ingredient3": "Chili Pepper",
        "Ingredient4": "Cheese",
        "Ingredient5": "-",
        "Energy": "1171",
        "sellPrice": "448",
    },
    {
        "Recipe": "French Fries",
        "Stars": "2",
        "Ingredient1": "Potato",
        "Ingredient2": "Canola",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "342",
        "sellPrice": "304",
    },
    {
        "Recipe": "Fruit Salad",
        "Stars": "1",
        "Ingredient1": "Fruit",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "450",
        "sellPrice": "25",
    },
    {
        "Recipe": "Fruit Sorbet",
        "Stars": "2",
        "Ingredient1": "Fruit",
        "Ingredient2": "Slush Ice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "857",
        "sellPrice": "222",
    },
    {
        "Recipe": "Fugu Sushi",
        "Stars": "3",
        "Ingredient1": "Fugu",
        "Ingredient2": "Rice",
        "Ingredient3": "Seaweed",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "3306",
        "sellPrice": "1485",
    },
    {
        "Recipe": "Gazpacho",
        "Stars": "4",
        "Ingredient1": "Cucumber",
        "Ingredient2": "Tomato",
        "Ingredient3": "Onion",
        "Ingredient4": "Spice",
        "Ingredient5": "-",
        "Energy": "831",
        "sellPrice": "563",
    },
    {
        "Recipe": "Gray Stuff",
        "Stars": "3",
        "Ingredient1": "Dairy/Oil",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Cocoa Bean",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1563",
        "sellPrice": "401",
    },
    {
        "Recipe": "Greek Pizza",
        "Stars": "5",
        "Ingredient1": "Spice",
        "Ingredient2": "Wheat",
        "Ingredient3": "Cheese",
        "Ingredient4": "Tomato",
        "Ingredient5": "Onion",
        "Energy": "1162",
        "sellPrice": "638",
    },
    {
        "Recipe": "Green Salad",
        "Stars": "2",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Lettuce",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "196",
        "sellPrice": "30",
    },
    {
        "Recipe": "Grilled Fish",
        "Stars": "1",
        "Ingredient1": "Fish",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "290",
        "sellPrice": "30",
    },
    {
        "Recipe": "Grilled Fish Entree",
        "Stars": "2",
        "Ingredient1": "Fish",
        "Ingredient2": "Vegetable",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "356",
        "sellPrice": "52",
    },
    {
        "Recipe": "Grilled Vegetables",
        "Stars": "1",
        "Ingredient1": "Corn",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "98",
        "sellPrice": "19",
    },
    {
        "Recipe": "Grilled Veggie Platter",
        "Stars": "3",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Vegetable",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "212",
        "sellPrice": "66",
    },
    {
        "Recipe": "Gumbo",
        "Stars": "5",
        "Ingredient1": "Okra",
        "Ingredient2": "Shrimp",
        "Ingredient3": "Chili Pepper",
        "Ingredient4": "Tomato",
        "Ingredient5": "Onion",
        "Energy": "2226",
        "sellPrice": "1093",
    },
    {
        "Recipe": "Hard-Boiled Eggs",
        "Stars": "1",
        "Ingredient1": "Egg",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "578",
        "sellPrice": "264",
    },
    {
        "Recipe": "Hearty Salad",
        "Stars": "3",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Lettuce",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "258",
        "sellPrice": "55",
    },
    {
        "Recipe": "Hors d'Oeuvres",
        "Stars": "1",
        "Ingredient1": "Spice",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "210",
        "sellPrice": "30",
    },
    {
        "Recipe": "Ice Cream",
        "Stars": "3",
        "Ingredient1": "Milk",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Slush Ice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1158",
        "sellPrice": "558",
    },
    {
        "Recipe": "Jam Waffles",
        "Stars": "4",
        "Ingredient1": "Fruit",
        "Ingredient2": "Wheat",
        "Ingredient3": "Egg",
        "Ingredient4": "Milk",
        "Ingredient5": "-",
        "Energy": "1843",
        "sellPrice": "709",
    },
    {
        "Recipe": "Kappa Maki",
        "Stars": "3",
        "Ingredient1": "Seaweed",
        "Ingredient2": "Cucumber",
        "Ingredient3": "Rice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "462",
        "sellPrice": "335",
    },
    {
        "Recipe": "Kronk's Spinach Puffs",
        "Stars": "3",
        "Ingredient1": "Spinach",
        "Ingredient2": "Cheese",
        "Ingredient3": "Canola",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "750",
        "sellPrice": "461",
    },
    {
        "Recipe": "Lancetfish Paella",
        "Stars": "5",
        "Ingredient1": "Lancetfish",
        "Ingredient2": "Shrimp",
        "Ingredient3": "Shellfish",
        "Ingredient4": "Tomato",
        "Ingredient5": "Rice",
        "Energy": "4550",
        "sellPrice": "1724",
    },
    {
        "Recipe": "Large Seafood Platter",
        "Stars": "5",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Shellfish",
        "Ingredient3": "Shellfish",
        "Ingredient4": "Shellfish",
        "Ingredient5": "Lemon",
        "Energy": "1810",
        "sellPrice": "340",
    },
    {
        "Recipe": "Leek Soup",
        "Stars": "1",
        "Ingredient1": "Leek",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "414",
        "sellPrice": "370",
    },
    {
        "Recipe": "Lemon Garlic Swordfish",
        "Stars": "3",
        "Ingredient1": "Lemon",
        "Ingredient2": "Garlic",
        "Ingredient3": "Swordfish",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "3713",
        "sellPrice": "1110",
    },
    {
        "Recipe": "Lemon Sorbet",
        "Stars": "2",
        "Ingredient1": "Lemon",
        "Ingredient2": "Slush Ice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1112",
        "sellPrice": "237",
    },
    {
        "Recipe": "Lobster Roll",
        "Stars": "5",
        "Ingredient1": "Lobster",
        "Ingredient2": "Wheat",
        "Ingredient3": "Lemon",
        "Ingredient4": "Butter",
        "Ingredient5": "Garlic",
        "Energy": "4928",
        "sellPrice": "1975",
    },
    {
        "Recipe": "Magura Sushi",
        "Stars": "4",
        "Ingredient1": "Tuna",
        "Ingredient2": "Rice",
        "Ingredient3": "Ginger",
        "Ingredient4": "Seaweed",
        "Ingredient5": "-",
        "Energy": "1206",
        "sellPrice": "413",
    },
    {
        "Recipe": "Maki",
        "Stars": "3",
        "Ingredient1": "Fish",
        "Ingredient2": "Seaweed",
        "Ingredient3": "Rice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "417",
        "sellPrice": "148",
    },
    {
        "Recipe": "Margherita Pizza",
        "Stars": "4",
        "Ingredient1": "Spice",
        "Ingredient2": "Tomato",
        "Ingredient3": "Cheese",
        "Ingredient4": "Wheat",
        "Ingredient5": "-",
        "Energy": "828",
        "sellPrice": "343",
    },
    {
        "Recipe": "Marinated Herring",
        "Stars": "2",
        "Ingredient1": "Onion",
        "Ingredient2": "Herring",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "723",
        "sellPrice": "305",
    },
    {
        "Recipe": "Mediterranean Salad",
        "Stars": "5",
        "Ingredient1": "Cucumber",
        "Ingredient2": "Tomato",
        "Ingredient3": "Onion",
        "Ingredient4": "Lettuce",
        "Ingredient5": "Spice",
        "Energy": "986",
        "sellPrice": "613",
    },
    {
        "Recipe": "Meringue Pie",
        "Stars": "4",
        "Ingredient1": "Wheat",
        "Ingredient2": "Egg",
        "Ingredient3": "Butter",
        "Ingredient4": "Lemon",
        "Ingredient5": "-",
        "Energy": "2014",
        "sellPrice": "667",
    },
    {
        "Recipe": "Mint Candy",
        "Stars": "2",
        "Ingredient1": "Mint",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "391",
        "sellPrice": "128",
    },
    {
        "Recipe": "Mint Chocolate",
        "Stars": "4",
        "Ingredient1": "Mint",
        "Ingredient2": "Cocoa Bean",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Butter",
        "Ingredient5": "-",
        "Energy": "1827",
        "sellPrice": "490",
    },
    {
        "Recipe": "Mint Sorbet",
        "Stars": "2",
        "Ingredient1": "Mint",
        "Ingredient2": "Slush Ice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "695",
        "sellPrice": "299",
    },
    {
        "Recipe": "Mushroom Pizza",
        "Stars": "4",
        "Ingredient1": "Mushroom",
        "Ingredient2": "Wheat",
        "Ingredient3": "Tomato",
        "Ingredient4": "Cheese",
        "Ingredient5": "-",
        "Energy": "837",
        "sellPrice": "351",
    },
    {
        "Recipe": "Mushu's Congee",
        "Stars": "5",
        "Ingredient1": "Rice",
        "Ingredient2": "Egg",
        "Ingredient3": "Ginger",
        "Ingredient4": "Garlic",
        "Ingredient5": "Mushroom",
        "Energy": "1658",
        "sellPrice": "753",
    },
    {
        "Recipe": "My Hero Cookie",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Vanilla",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "840",
        "sellPrice": "532",
    },
    {
        "Recipe": "Okra Soup",
        "Stars": "1",
        "Ingredient1": "Okra",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "99",
        "sellPrice": "136",
    },
    {
        "Recipe": "Omelet",
        "Stars": "3",
        "Ingredient1": "Egg",
        "Ingredient2": "Cheese",
        "Ingredient3": "Milk",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1751",
        "sellPrice": "882",
    },
    {
        "Recipe": "Onion Puffs",
        "Stars": "3",
        "Ingredient1": "Onion",
        "Ingredient2": "Cheese",
        "Ingredient3": "Egg",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1392",
        "sellPrice": "798",
    },
    {
        "Recipe": "Oyster Platter",
        "Stars": "2",
        "Ingredient1": "Oyster",
        "Ingredient2": "Lemon",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1155",
        "sellPrice": "367",
    },
    {
        "Recipe": "Pan-Fried Angler Fish",
        "Stars": "4",
        "Ingredient1": "Anglerfish",
        "Ingredient2": "Tomato",
        "Ingredient3": "Zucchini",
        "Ingredient4": "Potato",
        "Ingredient5": "-",
        "Energy": "4194",
        "sellPrice": "2550",
    },
    {
        "Recipe": "Pan-Seared Bass and Vegetables",
        "Stars": "3",
        "Ingredient1": "Bass",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Vegetable",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "428",
        "sellPrice": "79",
    },
    {
        "Recipe": "Pan-Seared Tilapia and Vegetables",
        "Stars": "3",
        "Ingredient1": "Tilapia",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Vegetable",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2228",
        "sellPrice": "884",
    },
    {
        "Recipe": "Pasta",
        "Stars": "2",
        "Ingredient1": "Wheat",
        "Ingredient2": "Tomato",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "117",
        "sellPrice": "30",
    },
    {
        "Recipe": "Pastry Cream and Fruits",
        "Stars": "5",
        "Ingredient1": "Fruit",
        "Ingredient2": "Fruit",
        "Ingredient3": "Fruit",
        "Ingredient4": "Milk",
        "Ingredient5": "Sugarcane",
        "Energy": "2332",
        "sellPrice": "497",
    },
    {
        "Recipe": "Pawpsicle",
        "Stars": "3",
        "Ingredient1": "Fruit",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Slush Ice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "987",
        "sellPrice": "265",
    },
    {
        "Recipe": "Peanut Butter Sandwich",
        "Stars": "2",
        "Ingredient1": "Peanut",
        "Ingredient2": "Wheat",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "592",
        "sellPrice": "262",
    },
    {
        "Recipe": "Peanut Butter Waffles",
        "Stars": "4",
        "Ingredient1": "Peanut",
        "Ingredient2": "Wheat",
        "Ingredient3": "Milk",
        "Ingredient4": "Egg",
        "Ingredient5": "-",
        "Energy": "1938",
        "sellPrice": "978",
    },
    {
        "Recipe": "Pickled Herring",
        "Stars": "4",
        "Ingredient1": "Herring",
        "Ingredient2": "Lemon",
        "Ingredient3": "Onion",
        "Ingredient4": "Spice",
        "Ingredient5": "-",
        "Energy": "1752",
        "sellPrice": "438",
    },
    {
        "Recipe": "Pizza",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Tomato",
        "Ingredient3": "Cheese",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "607",
        "sellPrice": "284",
    },
    {
        "Recipe": "Plain Snow Cones",
        "Stars": "1",
        "Ingredient1": "Slush Ice",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "410",
        "sellPrice": "180",
    },
    {
        "Recipe": "Poached Basil-Butter Sturgeon",
        "Stars": "4",
        "Ingredient1": "White Sturgeon",
        "Ingredient2": "Basil",
        "Ingredient3": "Butter",
        "Ingredient4": "Lemon",
        "Ingredient5": "-",
        "Energy": "4961",
        "sellPrice": "2246",
    },
    {
        "Recipe": "Porridge",
        "Stars": "2",
        "Ingredient1": "Milk",
        "Ingredient2": "Wheat",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "668",
        "sellPrice": "301",
    },
    {
        "Recipe": "Porridge with Fruits",
        "Stars": "3",
        "Ingredient1": "Milk",
        "Ingredient2": "Wheat",
        "Ingredient3": "Fruit",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1155",
        "sellPrice": "353",
    },
    {
        "Recipe": "Potato Leek Soup",
        "Stars": "5",
        "Ingredient1": "Potato",
        "Ingredient2": "Leek",
        "Ingredient3": "Milk",
        "Ingredient4": "Onion",
        "Ingredient5": "Garlic",
        "Energy": "1984",
        "sellPrice": "1431",
    },
    {
        "Recipe": "Potato Puffs",
        "Stars": "3",
        "Ingredient1": "Potato",
        "Ingredient2": "Cheese",
        "Ingredient3": "Egg",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1333",
        "sellPrice": "736",
    },
    {
        "Recipe": "Pottage",
        "Stars": "3",
        "Ingredient1": "Potato",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Spice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "487",
        "sellPrice": "233",
    },
    {
        "Recipe": "Pumpkin Puffs",
        "Stars": "3",
        "Ingredient1": "Pumpkin",
        "Ingredient2": "Cheese",
        "Ingredient3": "Egg",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1466",
        "sellPrice": "1489",
    },
    {
        "Recipe": "Pumpkin Soup",
        "Stars": "4",
        "Ingredient1": "Pumpkin",
        "Ingredient2": "Ginger",
        "Ingredient3": "Milk",
        "Ingredient4": "Vegetable",
        "Ingredient5": "-",
        "Energy": "1449",
        "sellPrice": "1515",
    },
    {
        "Recipe": "Puree",
        "Stars": "1",
        "Ingredient1": "Potato",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "230",
        "sellPrice": "151",
    },
    {
        "Recipe": "Ranch Salad",
        "Stars": "5",
        "Ingredient1": "Lettuce",
        "Ingredient2": "Bell Pepper",
        "Ingredient3": "Corn",
        "Ingredient4": "Tomato",
        "Ingredient5": "Onion",
        "Energy": "714",
        "sellPrice": "396",
    },
    {
        "Recipe": "Ratatouille",
        "Stars": "5",
        "Ingredient1": "Tomato",
        "Ingredient2": "Eggplant",
        "Ingredient3": "Zucchini",
        "Ingredient4": "Onion",
        "Ingredient5": "Spice",
        "Energy": "1582",
        "sellPrice": "992",
    },
    {
        "Recipe": "Red Fruit Pie",
        "Stars": "3",
        "Ingredient1": "Raspberry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1047",
        "sellPrice": "297",
    },
    {
        "Recipe": "Red Fruit Sorbet",
        "Stars": "4",
        "Ingredient1": "Raspberry",
        "Ingredient2": "Gooseberry",
        "Ingredient3": "Slush Ice",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "2179",
        "sellPrice": "359",
    },
    {
        "Recipe": "Roasted Asparagus",
        "Stars": "2",
        "Ingredient1": "Asparagus",
        "Ingredient2": "Canola",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "221",
        "sellPrice": "313",
    },
    {
        "Recipe": "Sake Maki",
        "Stars": "3",
        "Ingredient1": "Salmon",
        "Ingredient2": "Seaweed",
        "Ingredient3": "Rice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1101",
        "sellPrice": "323",
    },
    {
        "Recipe": "Sake Sushi",
        "Stars": "2",
        "Ingredient1": "Salmon",
        "Ingredient2": "Rice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1000",
        "sellPrice": "274",
    },
    {
        "Recipe": "Salad",
        "Stars": "1",
        "Ingredient1": "Lettuce",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "139",
        "sellPrice": "9",
    },
    {
        "Recipe": "Sauteed Mushrooms",
        "Stars": "2",
        "Ingredient1": "Mushroom",
        "Ingredient2": "Butter",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "712",
        "sellPrice": "286",
    },
    {
        "Recipe": "Savory Fish",
        "Stars": "2",
        "Ingredient1": "Fish",
        "Ingredient2": "Lemon",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "985",
        "sellPrice": "74",
    },
    {
        "Recipe": "Scrambled Egg",
        "Stars": "2",
        "Ingredient1": "Egg",
        "Ingredient2": "Cheese",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1070",
        "sellPrice": "520",
    },
    {
        "Recipe": "Seafood Appetizer",
        "Stars": "1",
        "Ingredient1": "Shellfish",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "242",
        "sellPrice": "54",
    },
    {
        "Recipe": "Seafood Pasta",
        "Stars": "3",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Wheat",
        "Ingredient3": "Milk",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "921",
        "sellPrice": "387",
    },
    {
        "Recipe": "Seafood Pie",
        "Stars": "3",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "813",
        "sellPrice": "331",
    },
    {
        "Recipe": "Seafood Platter",
        "Stars": "2",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Shellfish",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "458",
        "sellPrice": "116",
    },
    {
        "Recipe": "Seafood Salad",
        "Stars": "2",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Lettuce",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "349",
        "sellPrice": "68",
    },
    {
        "Recipe": "Seafood Soup",
        "Stars": "3",
        "Ingredient1": "Shellfish",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Vegetable",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "347",
        "sellPrice": "107",
    },
    {
        "Recipe": "Seared Rainbow Trout",
        "Stars": "3",
        "Ingredient1": "Rainbow Trout",
        "Ingredient2": "Tomato",
        "Ingredient3": "Onion",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "889",
        "sellPrice": "338",
    },
    {
        "Recipe": "Shake",
        "Stars": "1",
        "Ingredient1": "Dairy/Oil",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "144",
        "sellPrice": "130",
    },
    {
        "Recipe": "Simple Fried Perch",
        "Stars": "3",
        "Ingredient1": "Perch",
        "Ingredient2": "Butter",
        "Ingredient3": "Wheat",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1317",
        "sellPrice": "380",
    },
    {
        "Recipe": "Smoked Peanuts and Anglerfish",
        "Stars": "2",
        "Ingredient1": "Peanut",
        "Ingredient2": "Anglerfish",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "3960",
        "sellPrice": "2210",
    },
    {
        "Recipe": "Snow White's Gooseberry Pie",
        "Stars": "3",
        "Ingredient1": "Gooseberry",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1677",
        "sellPrice": "338",
    },
    {
        "Recipe": "Sole Meuiniere",
        "Stars": "4",
        "Ingredient1": "Sole",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "Lemon",
        "Ingredient5": "-",
        "Energy": "2337",
        "sellPrice": "637",
    },
    {
        "Recipe": "Souffle",
        "Stars": "4",
        "Ingredient1": "Egg",
        "Ingredient2": "Cheese",
        "Ingredient3": "Milk",
        "Ingredient4": "Butter",
        "Ingredient5": "-",
        "Energy": "2386",
        "sellPrice": "1230",
    },
    {
        "Recipe": "Sour Snow Cones",
        "Stars": "3",
        "Ingredient1": "Lemon",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Slush Ice",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1257",
        "sellPrice": "282",
    },
    {
        "Recipe": "Spaghetti Arrabbiata",
        "Stars": "3",
        "Ingredient1": "Wheat",
        "Ingredient2": "Tomato",
        "Ingredient3": "Chili Pepper",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "373",
        "sellPrice": "141",
    },
    {
        "Recipe": "Spicy Baked Bream",
        "Stars": "3",
        "Ingredient1": "Bream",
        "Ingredient2": "Butter",
        "Ingredient3": "Chili Pepper",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2075",
        "sellPrice": "767",
    },
    {
        "Recipe": "Steamed Fugu",
        "Stars": "3",
        "Ingredient1": "Fugu",
        "Ingredient2": "Ginger",
        "Ingredient3": "Garlic",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "3668",
        "sellPrice": "1484",
    },
    {
        "Recipe": "Sushi",
        "Stars": "2",
        "Ingredient1": "Fish",
        "Ingredient2": "Rice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "405",
        "sellPrice": "111",
    },
    {
        "Recipe": "Sweet and Sour Kingfish Steak",
        "Stars": "3",
        "Ingredient1": "Kingfish",
        "Ingredient2": "Lemon",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "2292",
        "sellPrice": "702",
    },
    {
        "Recipe": "Sweet Slush",
        "Stars": "2",
        "Ingredient1": "Sweets",
        "Ingredient2": "Slush Ice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "510",
        "sellPrice": "219",
    },
    {
        "Recipe": "Tamagoyaki",
        "Stars": "2",
        "Ingredient1": "Egg",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "689",
        "sellPrice": "310",
    },
    {
        "Recipe": "Tasty Salad",
        "Stars": "4",
        "Ingredient1": "Lettuce",
        "Ingredient2": "Cucumber",
        "Ingredient3": "Vegetable",
        "Ingredient4": "Spice",
        "Ingredient5": "-",
        "Energy": "678",
        "sellPrice": "311",
    },
    {
        "Recipe": "Tasty Veggies",
        "Stars": "2",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Spice",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "271",
        "sellPrice": "52",
    },
    {
        "Recipe": "Tekka Maki",
        "Stars": "4",
        "Ingredient1": "Tuna",
        "Ingredient2": "Seaweed",
        "Ingredient3": "Rice",
        "Ingredient4": "Soya",
        "Ingredient5": "-",
        "Energy": "984",
        "sellPrice": "366",
    },
    {
        "Recipe": "Teriyaki Salmon",
        "Stars": "5",
        "Ingredient1": "Salmon",
        "Ingredient2": "Soya",
        "Ingredient3": "Ginger",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "Rice",
        "Energy": "1726",
        "sellPrice": "637",
    },
    {
        "Recipe": "Tomato Soup",
        "Stars": "1",
        "Ingredient1": "Tomato",
        "Ingredient2": "-",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "83",
        "sellPrice": "26",
    },
    {
        "Recipe": "Tropical Pop",
        "Stars": "4",
        "Ingredient1": "Fruit",
        "Ingredient2": "Coconut",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Slush Ice",
        "Ingredient5": "-",
        "Energy": "1989",
        "sellPrice": "347",
    },
    {
        "Recipe": "Tuna Burger",
        "Stars": "5",
        "Ingredient1": "Tuna",
        "Ingredient2": "Wheat",
        "Ingredient3": "Lemon",
        "Ingredient4": "Onion",
        "Ingredient5": "Vegetable",
        "Energy": "1940",
        "sellPrice": "504",
    },
    {
        "Recipe": "Vanilla Ice Cream",
        "Stars": "4",
        "Ingredient1": "Vanilla",
        "Ingredient2": "Milk",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Slush Ice",
        "Ingredient5": "-",
        "Energy": "1475",
        "sellPrice": "688",
    },
    {
        "Recipe": "Vegetable Soup",
        "Stars": "2",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Vegetable",
        "Ingredient3": "-",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "152",
        "sellPrice": "40",
    },
    {
        "Recipe": "Vegetarian Pizza",
        "Stars": "5",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Wheat",
        "Ingredient4": "Tomato",
        "Ingredient5": "Cheese",
        "Energy": "790",
        "sellPrice": "376",
    },
    {
        "Recipe": "Vegetarian Stew",
        "Stars": "3",
        "Ingredient1": "Potato",
        "Ingredient2": "Carrot",
        "Ingredient3": "Onion",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "617",
        "sellPrice": "475",
    },
    {
        "Recipe": "Vegetarian Taco",
        "Stars": "4",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Corn",
        "Ingredient3": "Chili Pepper",
        "Ingredient4": "Cheese",
        "Ingredient5": "-",
        "Energy": "943",
        "sellPrice": "435",
    },
    {
        "Recipe": "Veggie Casserole",
        "Stars": "4",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Vegetable",
        "Ingredient3": "Spice",
        "Ingredient4": "Cheese",
        "Ingredient5": "-",
        "Energy": "867",
        "sellPrice": "355",
    },
    {
        "Recipe": "Veggie Pasta",
        "Stars": "3",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Tomato",
        "Ingredient3": "Wheat",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "175",
        "sellPrice": "54",
    },
    {
        "Recipe": "Veggie Pie",
        "Stars": "3",
        "Ingredient1": "Vegetable",
        "Ingredient2": "Wheat",
        "Ingredient3": "Butter",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "651",
        "sellPrice": "290",
    },
    {
        "Recipe": "Veggie Skewers",
        "Stars": "4",
        "Ingredient1": "Mushroom",
        "Ingredient2": "Zucchini",
        "Ingredient3": "Onion",
        "Ingredient4": "Bell Pepper",
        "Ingredient5": "-",
        "Energy": "767",
        "sellPrice": "427",
    },
    {
        "Recipe": "Waffles",
        "Stars": "4",
        "Ingredient1": "Wheat",
        "Ingredient2": "Egg",
        "Ingredient3": "Milk",
        "Ingredient4": "Sugarcane",
        "Ingredient5": "-",
        "Energy": "1455",
        "sellPrice": "706",
    },
    {
        "Recipe": "Walleye en Papillote",
        "Stars": "4",
        "Ingredient1": "Walleye",
        "Ingredient2": "Basil",
        "Ingredient3": "Oregano",
        "Ingredient4": "Vegetable",
        "Ingredient5": "-",
        "Energy": "3707",
        "sellPrice": "1741",
    },
    {
        "Recipe": "Wedding Cake",
        "Stars": "5",
        "Ingredient1": "Vanilla",
        "Ingredient2": "Butter",
        "Ingredient3": "Sugarcane",
        "Ingredient4": "Egg",
        "Ingredient5": "Wheat",
        "Energy": "1680",
        "sellPrice": "785",
    },
    {
        "Recipe": "Wonderland Cookies",
        "Stars": "4",
        "Ingredient1": "Butter",
        "Ingredient2": "Sugarcane",
        "Ingredient3": "Vanilla",
        "Ingredient4": "Wheat",
        "Ingredient5": "-",
        "Energy": "970",
        "sellPrice": "406",
    },
    {
        "Recipe": "Zucchini Puffs",
        "Stars": "3",
        "Ingredient1": "Zucchini",
        "Ingredient2": "Cheese",
        "Ingredient3": "Egg",
        "Ingredient4": "-",
        "Ingredient5": "-",
        "Energy": "1216",
        "sellPrice": "632",
    },
]

/*{
        "Recipe": "",
        "Stars": "",
        "Ingredient1": "",
        "Ingredient2": "",
        "Ingredient3": "",
        "Ingredient4": "",
        "Ingredient5": "",
        "Energy": "",
        "sellPrice": "",
    },
*/